desc "Deploy a new beta build to Google Play"
lane :production do
  build_number = number_of_commits()+100
  Dir.chdir "../.." do
    sh("flutter", "packages", "get")
    sh("flutter", "clean")
    sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
  end
  upload_to_play_store(track: 'production', aab: '../build/app/outputs/bundle/release/app-release.aab')
  slack(
    message: “Findoo Proveedor Desplegado: #{build_number}“,
    success: true,
    slack_url: 'https://hooks.slack.com/services/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'
    )
end


